name	'abrt'
version '0.2.0'
source 'https://github.com/cernops/puppet-abtr'
author 'CERNOps'
license 'GNU General Public License, Version 3'
summary 'Configuring abrt (Daemon monitoring crashes)'
description 'Configuring abrt (Daemon monitoring crashes)'
project_page 'https://github.com/cernops/puppet-abtr'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
